steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/synchub-backend', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/synchub-backend']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'synchub-cloudrun',
        '--image', 'gcr.io/$PROJECT_ID/synchub-backend',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--set-env-vars',
        'DJANGO_SECRET_KEY=$(DJANGO_SECRET_KEY),GOOGLE_CLIENT_ID=$(GOOGLE_CLIENT_ID),GOOGLE_CLIENT_SECRET=$(GOOGLE_CLIENT_SECRET),DB_NAME=postgres,DB_USER=postgres,DB_PASSWORD=$(DB_PASSWORD),DB_HOST=/cloudsql/synchub-456918:us-central1:synchubsql,DB_PORT=5432,DJANGO_ALLOWED_HOSTS=synchub-cloudrun-834454980092.us-central1.run.app,USE_GCS=True,GS_BUCKET_NAME=synchub-bucket,GS_STATIC_BUCKET_NAME=synchub-bucket'
      ]
    secretEnv: ['DJANGO_SECRET_KEY', 'GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET', 'DB_PASSWORD']

secrets:
- secretEnv:
    DJANGO_SECRET_KEY: projects/$PROJECT_ID/secrets/django_secret_key/versions/latest
    GOOGLE_CLIENT_ID: projects/$PROJECT_ID/secrets/google_client_id/versions/latest
    GOOGLE_CLIENT_SECRET: projects/$PROJECT_ID/secrets/google_client_secret/versions/latest
    DB_PASSWORD: projects/$PROJECT_ID/secrets/db_password/versions/latest

images:
  - 'gcr.io/$PROJECT_ID/synchub-backend' 