import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "../../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-50 min-h-screen flex">
        <aside className="w-56 bg-blue-800 text-white flex flex-col py-8 px-4 min-h-screen">
          <h2 className="text-2xl font-bold mb-8 text-center">GrocerySync Hub</h2>
          <nav className="flex flex-col gap-4">
            <Link href="/dashboard" className="hover:bg-blue-700 rounded px-3 py-2">Dashboard</Link>
            <Link href="/retailers" className="hover:bg-blue-700 rounded px-3 py-2">Retailers</Link>
            <Link href="/logs" className="hover:bg-blue-700 rounded px-3 py-2">Logs</Link>
            <Link href="/login" className="mt-8 hover:bg-blue-700 rounded px-3 py-2">Logout</Link>
          </nav>
        </aside>
        <main className="flex-1 flex flex-col">
          <header className="bg-white shadow px-8 py-4 flex items-center justify-between">
            <span className="text-lg font-semibold text-blue-800">Support Edition</span>
          </header>
          <section className="flex-1 p-8">{children}</section>
        </main>
      </body>
    </html>
  );
}
